name: Testing OIDC

on:
  push:
    branches: [ oidc-test ]

jobs:
  test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/stv-io/tg-gcp-ci-tools-image:v0.2.4
      options: --user root # https://github.com/actions/checkout/issues/1014
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: "projects/416513167694/locations/global/workloadIdentityPools/l25t-oidc-gh-pool/providers/l25t-oidc-gh-provider"
          service_account: "github-actions-oidc-sa@stejfen-lab-host-one.iam.gserviceaccount.com"
      - name: test
        env:
          TF_VERSION: 1.4.6
          TG_VERSION: 0.45.4
        run: |
          gcloud iam service-accounts list --project=stejfen-lab-host-one 

